theme: jekyll-theme-dinky
title: Keizaal
show_downloads: true
wabbajack:
  wabbajack_url: https://www.wabbajack.org/#/
pages:
  mainpage_url: https://pierredespereaux.github.io/Keizaal/
  installationguide_url: https://pierredespereaux.github.io/Keizaal/INSTALLATIONGUIDE.html
  troubleshooting_url: https://pierredespereaux.github.io/Keizaal/TROUBLESHOOTING.html
  changelog_url: https://pierredespereaux.github.io/Keizaal//CHANGELOG.html
  credits_url: https://pierredespereaux.github.io/Keizaal/CREDITS.html
